### ISSUE TITLE
Gesture to back

### ISSUE THREAD

**Issue by Irineu333** [Irineu333/SpeakTouch#86]
Implement a gesture to return to the previous screen or app. The _down and left_ gesture is generally used for this.

**Comment by PatrykMis** [comment]
Do we really need this? I use navigation gestures from past a year (instead of three-button navigation bar) and it works well by swiping two fingers left or right from the edge of the screen for back. Recent apps list and home can be activated as well. Of course it works perfectly in TalkBack and in SpeakTouch too.

**Comment by Irineu333** [comment]
Not everyone use it this way, and the gesture to return is present in all other readers.
